const AppConfig = {
    baseUrl: 'https://graph.facebook.com',
    token: 'EAAMlpyZCc7cMBOZBfk0D2PxMnj1CBdGxcB2gHPVgTXS90keH8JtSYiZCOAZBIz4BwAR0tZAk4ZBArZBk7kmhOHaFqSAQdUvZCvCxMcy9kXcVt6NqnG62uV7xZAfaqlWvQFxbZCyUCci4ajWyvUSAJDTzkLYo1SCIugkvoEpr1JsQvFrh8n1TM9kwyC144eWzmDIrbeFwdVyslGf4gBSj7DzcpJWgVXFIhULa34K1oZD'
}